### ISSUE TITLE
Global path question

### ISSUE THREAD

**Issue by loremaps** [jonschlinkert/npm-paths#2]
[global-modules](https://github.com/jonschlinkert/global-modules) returns my correct path:
`/home/username/.npm-global/lib/node_modules`

Shouldn't [npm-paths](https://github.com/jonschlinkert/npm-paths) return it as well? Or should we use [global-modules](https://github.com/jonschlinkert/global-modules)?

(from more info please check graphql-cli/graphql-cli#60 )

**Comment by doowb** [comment]
@loremaps there might have been a bug fixed in a newer version of a dependency. I think `global-modules` just needs to be updated to the latest version.

Will you clone this library and install the latest version of `global-modules` as a dependency, then try running the `npm-paths` function? This will let me know if more needs to be done.

**Comment by loremaps** [comment]
@doowb updating `global-module` to `1.0.0` did the trick. :+1:
